modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
logoFile = "cbc_military_supplement_fix.png"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "cbcmoreshells"
type = "required"
reason = "This patch targets CBC Military Supplement 2.1.0 for Minecraft 1.21.1"
versionRange = "[2.1.0-1.21.1]"
ordering = "BEFORE"
side = "BOTH"
